### ISSUE TITLE
Load time before Payment option becomes available

### ISSUE THREAD

**Issue by wouter-dev** [medusajs/gatsby-starter-medusa#16]
It takes a very long time (seconds) before the Stripe payment provider becomes available, is there a way to solve this?

**Comment by kasperkristensen** [comment]
Hi @wouter-dev, it's true that Stripe sometimes takes a second to load. If you think this is too slow, then one thing you could do is to already render it before the final step, and make it non interactable until all the previous steps are completed 😄
